apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-booking-kube-prometheus-stack
  namespace: observability
  labels:
    app: kube-prometheus-stack-alertmanager
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: default
      group_by:
        - namespace
        - job
        - alertname

      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h

      routes:

        # Critical alerts
        - matchers:
            - severity="critical"
          receiver: critical
          group_wait: 10s
          repeat_interval: 1h

        # SLO alerts
        - matchers:
            - alertname=~"SLO.*"
          receiver: slo-alerts
          repeat_interval: 4h

        # Frontend
        - matchers:
            - job="frontend"
          receiver: frontend

        # Auth
        - matchers:
            - job="auth"
          receiver: auth

        # Booking
        - matchers:
            - job="book"
          receiver: booking

        # Search
        - matchers:
            - job="search"
          receiver: search

        # Payment
        - matchers:
            - job="payment"
          receiver: payment

        # Notification
        - matchers:
            - job="notification"
          receiver: notification

    receivers:

      - name: default
        # webhook_configs:

      - name: critical
        # slack_configs:

      - name: slo-alerts
        # slack_configs:

      - name: frontend
        # slack_configs:

      - name: auth
        # slack_configs:

      - name: booking
        # slack_configs:

      - name: search
        # slack_configs:

      - name: payment
        # slack_configs:

      - name: notification
        # slack_configs:

    inhibit_rules:

      - source_matchers:
          - severity="critical"
        target_matchers:
          - severity="warning"
        equal:
          - namespace
          - job
          - alertname