apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: frontend-service-rules
  namespace: observability
  labels:
    app: kube-prometheus-stack
    release: booking
spec:
  groups:
    - name: frontend.alerts
      rules:

        - alert: FrontendHighErrorRate
          expr: |
            (
              sum(rate(http_request_duration_seconds_count{job="frontend",status_code=~"5.."}[5m]))
              /
              sum(rate(http_request_duration_seconds_count{job="frontend"}[5m]))
            ) > 0.05
          for: 2m
          labels:
            severity: critical
            service: frontend

        - alert: FrontendHighLatency
          expr: |
            histogram_quantile(
              0.99,
              sum(rate(http_request_duration_seconds_bucket{job="frontend"}[5m])) by (le)
            ) > 1
          for: 5m
          labels:
            severity: warning
            service: frontend

        - alert: FrontendPodNotReady
          expr: kube_pod_status_ready{condition="true",pod=~".*-frontend-.*"}==0
          for: 5m
          labels:
            severity: critical
            service: frontend