apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: payment-service-rules
  namespace: observability
  labels:
    app: kube-prometheus-stack
    release: booking
spec:
  groups:
    - name: payment.alerts
      rules:

        - alert: PaymentHighErrorRate
          expr: |
            (
              sum(rate(http_request_duration_seconds_count{job="payment",status_code=~"5.."}[5m]))
              /
              sum(rate(http_request_duration_seconds_count{job="payment"}[5m]))
            ) > 0.05
          for: 2m
          labels:
            severity: critical
            service: payment

        - alert: PaymentHighLatency
          expr: |
            histogram_quantile(
              0.99,
              sum(rate(http_request_duration_seconds_bucket{job="payment"}[5m])) by (le)
            ) > 1
          for: 5m
          labels:
            severity: warning
            service: payment

        - alert: PaymentPodNotReady
          expr: kube_pod_status_ready{condition="true",pod=~".*-payment-.*"}==0
          for: 5m
          labels:
            severity: critical
            service: payment